language: node_js
node_js:
 - "8"
script:
 - echo "Deploy!"
install:
 - npm install -g firebase-tools
 - cd functions/
 - npm install
 - cd ..
after_success:
 - firebase target:clear hosting ambassadors-yogi-run
 - firebase target:apply hosting ambassadors-yogi-run ambassadors-yogi-run
 - firebase deploy --project yogi-run --only hosting:ambassadors-yogi-run --token $FIREBASE_TOKEN
